export const TYPE = {FNAME:"FNAME",LNAME:"LNAME",EMAIL:"EMAIL",BIRTHDATE:"BIRTHDATE", PASSWORD:"PASSWORD",CONFIRMED:"CONFIRMED",
              ADDRESS:"ADDRESS",CITY:"CITY", STATE:"STATE",PHONE:"PHONE",COUNTRY:"COUNTRY",ZIP:"ZIP"};
